package org.primesoft.asyncworldedit.worldedit;

/**
 * Stub for the API to compile
 * All operations that can by done in async mode
 * @author SBPrime
 */
public enum WorldeditOperations 
{
    undo,
    redo,
    fillXZ,
    removeAbove,
    removeBelow,
    removeNear,
    setBlocks,
    replaceBlocks,
    makeCuboidFaces,
    makeCuboidWalls,
    overlayCuboidBlocks,
    naturalizeCuboidBlocks,
    stackCuboidRegion,
    moveCuboidRegion,
    drainArea,
    fixLiquid,
    makeCylinder,
    makeSphere,
    makePyramid,
    thaw,
    simulateSnow,
    green,
    makePumpkinPatches,
    makeForest,
    makeShape,
    deformRegion,
    hollowOutRegion,
    paste,
    copy,
    cut,
    regenerate,
    center,
    drawLine,
    drawSpline,
    makeBiomeShape,
    forest,
    flora,
    setBiome,
    loadSchematic,
    saveSchematic,
    craftScript,
    makeFaces,
    makeWalls,
    overlayBlocks,
    naturalizeBlocks,
    stackRegion,
    moveRegion,
}
