name: AsyncWorldEdit
main: org.primesoft.asyncworldedit.AsyncWorldEditBukkit
version: 3.4.11
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin attaches into WorldEdit and makes it asynchronous.
authors: [SBPrime]
loadbefore: [WorldEdit]
load: STARTUP
commands:
permissions:
