name: AsyncWorldEdit-ActionBarAPI
main: org.primesoft.asyncworldedit.progressDisplay.ActionBarAPIBackend
version: 3.3.0
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin provides ActionBarAPI progress display backend for AsyncWorldEdit
authors: [SBPrime]
depend: [ActionBarAPI]

