name: AsyncWorldEditInjector
main: org.primesoft.asyncworldedit.injector.InjectorBukkit
version: 2.3.0
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin attaches into WorldEdit and makes it asynchronous.
authors: [SBPrime]
loadbefore: [WorldEdit, AsyncWorldEdit]
load: STARTUP
