name: AsyncWorldEdit-PlotMeCore016
main: org.primesoft.asyncworldedit.plotme.PlotMeCoreFix_016
version: 3.3.0
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin implements PlotMeFix for PlotMeCore 0.16
authors: [SBPrime]
depend: [PlotMe]
