name: AsyncWorldEdit-WelcomeTitle
main: org.primesoft.asyncworldedit.progressDisplay.WelcomeTitleBackend
version: 2.3.0
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin provides WelcomeTitle progress display backend for AsyncWorldEdit
authors: [SBPrime]
depend: [AsyncWorldEdit, WelcomeTitle]

